<?php

declare(strict_types=1);

/**
 * Local demo server — acts as both a publisher (using the SDK) and a mock Supertab Connect API.
 *
 * Usage: php -S localhost:8080 demo/server.php
 *
 * Requires demo/.local-key.pem to exist (generated by run-local.php).
 */

require __DIR__ . '/../vendor/autoload.php';

use Firebase\JWT\JWT;
use Supertab\Connect\Enum\EnforcementMode;
use Supertab\Connect\Http\HttpClient;
use Supertab\Connect\Http\HttpClientInterface;
use Supertab\Connect\Http\RequestContext;
use Supertab\Connect\Result\AllowResult;
use Supertab\Connect\Result\BlockResult;
use Supertab\Connect\SupertabConnect;

// ── Configuration ────────────────────────────────────────

$port = $_ENV['DEMO_PORT'] ?? getenv('DEMO_PORT') ?: '8080';
$baseUrl = "http://localhost:{$port}";
$keyFile = __DIR__ . '/.local-key.pem';

if (! file_exists($keyFile)) {
    http_response_code(500);
    echo "Missing key file: {$keyFile}\nRun 'composer demo:local' to start the demo properly.\n";
    exit(1);
}

// ── Load key material ────────────────────────────────────

$pem = file_get_contents($keyFile);
$privateKey = openssl_pkey_get_private($pem);
$details = openssl_pkey_get_details($privateKey);
$kid = 'demo-key-1';

// Build JWKS from the public key's EC coordinates
$jwksJson = json_encode([
    'keys' => [[
        'kty' => 'EC',
        'crv' => 'P-256',
        'kid' => $kid,
        'use' => 'sig',
        'alg' => 'ES256',
        'x' => rtrim(strtr(base64_encode($details['ec']['x']), '+/', '-_'), '='),
        'y' => rtrim(strtr(base64_encode($details['ec']['y']), '+/', '-_'), '='),
    ]],
]);

// ── Custom HTTP client (intercepts JWKS self-requests) ───

$httpClient = new class($jwksJson) implements HttpClientInterface
{
    public function __construct(private string $jwksJson) {}

    public function get(string $url, array $headers = []): array
    {
        if (str_contains($url, '.well-known/jwks.json')) {
            return ['statusCode' => 200, 'body' => $this->jwksJson];
        }

        return (new HttpClient)->get($url, $headers);
    }

    public function post(string $url, string $body, array $headers = []): array
    {
        return (new HttpClient)->post($url, $body, $headers);
    }
};

// ── SDK publisher instance ───────────────────────────────

SupertabConnect::resetInstance();

$connect = new SupertabConnect(
    apiKey: 'demo-local-key',
    enforcement: EnforcementMode::STRICT,
    baseUrl: $baseUrl,
    httpClient: $httpClient,
);

// ── Routing ──────────────────────────────────────────────

$uri = parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH);
$method = $_SERVER['REQUEST_METHOD'];

switch (true) {
    // ── Protected content ────────────────────────────────
    case $uri === '/article' && $method === 'GET':
        $result = $connect->handleRequest(RequestContext::fromGlobals());

        if ($result instanceof AllowResult) {
            header('Content-Type: text/html; charset=UTF-8');
            echo <<<'HTML'
<!DOCTYPE html>
<html>
<head><title>Premium Article</title></head>
<body>
<h1>The Future of AI-Powered Content Licensing</h1>
<p>This is a premium article protected by the RSL (Rights and Sharing License) standard.</p>
<p>If you can read this, your license token was verified successfully by the Supertab Connect SDK.</p>
<p>The publisher earns revenue while bots get legitimate access to content. Everyone wins.</p>
</body>
</html>
HTML;
        } elseif ($result instanceof BlockResult) {
            // Headers and status already set by SupertabConnect::send()
            echo $result->body;
        }
        break;

        // ── License XML ──────────────────────────────────────
    case $uri === '/license.xml' && $method === 'GET':
        header('Content-Type: application/xml; charset=UTF-8');
        echo <<<XML
<?xml version="1.0" encoding="UTF-8"?>
<rsl xmlns="https://rslstandard.org/rsl">
  <content url="{$baseUrl}/*" server="{$baseUrl}">
    <license type="application/vnd.readium.license.status.v1.0+json">
      <link rel="self" href="{$baseUrl}/license" />
    </license>
  </content>
</rsl>
XML;
        break;

        // ── Mock token endpoint ──────────────────────────────
    case $uri === '/token' && $method === 'POST':
        $input = file_get_contents('php://input');
        parse_str($input, $params);

        $grantType = $params['grant_type'] ?? '';
        if ($grantType !== 'client_credentials') {
            http_response_code(400);
            header('Content-Type: application/json');
            echo json_encode(['error' => 'unsupported_grant_type']);
            break;
        }

        // Extract client ID from Basic auth (accept any credentials)
        $auth = $_SERVER['HTTP_AUTHORIZATION'] ?? '';
        $clientId = 'anonymous';
        if (str_starts_with($auth, 'Basic ')) {
            $decoded = base64_decode(substr($auth, 6), true);
            if ($decoded !== false && str_contains($decoded, ':')) {
                $clientId = explode(':', $decoded, 2)[0];
            }
        }

        $token = JWT::encode(
            [
                'iss' => $baseUrl . '/local',
                'aud' => $baseUrl,
                'sub' => $clientId,
                'license_id' => 'lic_demo_' . bin2hex(random_bytes(4)),
                'scope' => 'content:read',
                'iat' => time(),
                'exp' => time() + 3600,
            ],
            $privateKey,
            'ES256',
            $kid,
        );

        header('Content-Type: application/json');
        echo json_encode(['access_token' => $token, 'token_type' => 'License', 'expires_in' => 3600]);
        break;

        // ── JWKS endpoint (for transparency / debugging) ─────
    case $uri === '/.well-known/jwks.json/platform' && $method === 'GET':
        header('Content-Type: application/json');
        echo $jwksJson;
        break;

        // ── 404 ──────────────────────────────────────────────
    default:
        http_response_code(404);
        echo "Not found: {$method} {$uri}\n";
        break;
}
